import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
//package javaapplication3;

/**
 *
 * @author Darek
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jTextField5 = new javax.swing.JTextField();
        jComboBox7 = new javax.swing.JComboBox();
        jTextField6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox();
        jTextField7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jTextField9 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox();
        jTextField10 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox();
        jComboBox13 = new javax.swing.JComboBox();
        jComboBox14 = new javax.swing.JComboBox();
        jComboBox15 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea(20,5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Zadanie 1: Metoda graficzna");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Rozwi¹zanie graficzne:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField1.setText("2");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("x");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel4.setText("1");

        jComboBox1.setMaximumRowCount(2);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        jComboBox1.setSelectedIndex(1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField2.setText("6");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("x");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setText("2");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("->");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "max", "min" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Ograniczenia:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("x");

        jComboBox4.setMaximumRowCount(2);
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField3.setText("2");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("x");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel11.setText("1");

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField4.setText("3");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel12.setText("2");

        jComboBox6.setMaximumRowCount(2);
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ">=", "<=" }));
        jComboBox6.setSelectedIndex(1);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField5.setText("6");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ">=", "<=" }));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField6.setText("1");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("x");

        jComboBox8.setMaximumRowCount(2);
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        jComboBox8.setSelectedIndex(1);
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField7.setText("1");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("x");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel15.setText("1");

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField8.setText("1");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel16.setText("2");

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ">=", "<=" }));

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField9.setText("1");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("x");

        jComboBox11.setMaximumRowCount(2);
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        jComboBox11.setSelectedIndex(1);
        jComboBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox11ActionPerformed(evt);
            }
        });

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField10.setText("2");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setText("x");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel19.setText("1");

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField11.setText("1");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel20.setText("2");

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        jComboBox12.setSelectedIndex(1);

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        jComboBox14.setSelectedIndex(1);

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));

        jButton1.setText("Narysuj i oblicz");

        /*jTextArea1.setColumns(20);
        jTextArea1.setRows(5);*/
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jTextField9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(jButton1)))
                .addGap(0, 75, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1)
                        .addComponent(jLabel3)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3)
                        .addComponent(jLabel9)
                        .addComponent(jLabel12)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField5)
                        .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel16)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField8)
                    .addComponent(jTextField7)
                    .addComponent(jTextField6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        int a = jComboBox8.getSelectedIndex();
        System.out.print(a);
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jComboBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox11ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    private void jTextArea1ActionPerformed1(java.awt.event.ActionEvent evt){

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	/*Integer liczba= new Integer (null);
    	liczba = Integer.parseInt(jTextField1.getText());
    	System.out.print("Cos ashdiuasnfdckjsdnfiubdsaiuhf" + liczba);
    	*/
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
    	/**
    	 * ZMIENNE FUNKCJI
    	 */
    	boolean f1 =true,
    			f2 = true,
    			f3=true,
    			brakRozwiazan=false;//flagi do sprawdzenia czy sa punkty przeciecia dwoch prostych
    	
    	//funkcja celu
    	double ac=2.0;
    	double bc=-6.0;
    	boolean max=true;//czy nasza funkcja jest do max czy do min
    	//funkcja 1
    	double a1=3.0;
    	double b1=2.0;
    	double c1=6.0;
    	String znak1 = "<=";
    	
    	//funkcja 2
    	double a2=1.0;
    	double b2=-1.0;
    	double c2=-1.0;
    	String znak2 = ">=";
    	
    	//funkcja 3
    	double a3=-1.0;
    	double b3=-2.0;
    	double c3=1.0;
    	String znak3 = ">=";
    	
    	/**
    	 * OBLICZENIA DO RYSOWANIA FUNKCJI
    	 */
    	//--------------------------------------------------------------------------------------------------------------------
    	//-------------------------------------------------FUNKCJA CELU-------------------------------------------------------
    	//--------------------------------------------------------------------------------------------------------------------
    	double[][] tabcelu = new double[2][6];
    	//x1 do wyliczenia x2
    	tabcelu[0][0]=0.0;
    	tabcelu[0][1]=2.0;
    	tabcelu[0][2]=4.0;
    	tabcelu[0][3]=6.0;
    	tabcelu[0][4]=8.0;
    	tabcelu[0][5]=10.0;
    	
    	//wyliczanie x2
    	tabcelu[1][0]=(-ac/bc)*tabcelu[0][0];
    	tabcelu[1][1]=(-ac/bc)*tabcelu[0][1];
    	tabcelu[1][2]=(-ac/bc)*tabcelu[0][2];
    	tabcelu[1][3]=(-ac/bc)*tabcelu[0][3];
    	tabcelu[1][4]=(-ac/bc)*tabcelu[0][4];
    	tabcelu[1][5]=(-ac/bc)*tabcelu[0][5];
    	
    	//---------------------------------------------------------------------------------------------------------------
    	//----------------------------------------------FUNKCJA 1--------------------------------------------------------
    	//---------------------------------------------------------------------------------------------------------------
    	double[][] tab1 = new double[2][6];
    	tab1[0][0]=0.0;
    	tab1[0][1]=2.0;
    	tab1[0][2]=4.0;
    	tab1[0][3]=6.0;
    	tab1[0][4]=8.0;
    	tab1[0][5]=10.0;
    	
    	//wyliczanie x2
    	if(b1<0){
    		if(znak1=="<="){
    			 znak1 = ">=";
    		}
    		if(znak1==">="){
   			 znak1 = "<=";
    		}
    	}
    	tab1[1][0]=(-a1*tab1[0][0]+c1)/b1;
    	tab1[1][1]=(-a1*tab1[0][1]+c1)/b1;
    	tab1[1][2]=(-a1*tab1[0][2]+c1)/b1;
    	tab1[1][3]=(-a1*tab1[0][3]+c1)/b1;
    	tab1[1][4]=(-a1*tab1[0][4]+c1)/b1;
    	tab1[1][5]=(-a1*tab1[0][5]+c1)/b1;
    	tab1[1][0]=(-a1/b1)*tab1[0][0]+(c1/b1);
    	tab1[1][1]=(-a1/b1)*tab1[0][1]+(c1/b1);
    	tab1[1][2]=(-a1/b1)*tab1[0][2]+(c1/b1);
    	tab1[1][3]=(-a1/b1)*tab1[0][3]+(c1/b1);
    	tab1[1][4]=(-a1/b1)*tab1[0][4]+(c1/b1);
    	tab1[1][5]=(-a1/b1)*tab1[0][5]+(c1/b1);
    	    	//tab1[1][0]=(-a1*tab1[0][0]+c1)/b1;
    	
    	//---------------------------------------------------------------------------------------------------------------
    	//---------------------------------------FUNKCJA 2---------------------------------------------------------------
    	//---------------------------------------------------------------------------------------------------------------
    	double[][] tab2 = new double[2][6];
    	tab2[0][0]=0.0;
    	tab2[0][1]=2.0;
    	tab2[0][2]=4.0;
    	tab2[0][3]=6.0;
    	tab2[0][4]=8.0;
    	tab2[0][5]=10.0;
    	
    	//wyliczanie x2
    	if(b2<0){
    		if(znak2=="<="){
    			 znak2 = ">=";
    		}
    		if(znak2==">="){
   			 znak2 = "<=";
    		}
    	}
    	tab2[1][0]=(-a2/b2)*tab2[0][0]+(c2/b2);
    	tab2[1][1]=(-a2/b2)*tab2[0][1]+(c2/b2);
    	tab2[1][2]=(-a2/b2)*tab2[0][2]+(c2/b2);
    	tab2[1][3]=(-a2/b2)*tab2[0][3]+(c2/b2);
    	tab2[1][4]=(-a2/b2)*tab2[0][4]+(c2/b2);
    	tab2[1][5]=(-a2/b2)*tab2[0][5]+(c2/b2);
    	
    	
    	//---------------------------------------------------------------------------------------------------------------
    	//---------------------------------------FUNKCJA 3---------------------------------------------------------------
    	//---------------------------------------------------------------------------------------------------------------
    	double[][] tab3 = new double[2][6];
    	tab3[0][0]=0.0;
    	tab3[0][1]=2.0;
    	tab3[0][2]=4.0;
    	tab3[0][3]=6.0;
    	tab3[0][4]=8.0;
    	tab3[0][5]=10.0;
    	
    	//wyliczanie x2
    	if(b3<0){
    		if(znak3=="<="){
    			 znak3 = ">=";
    		}
    		if(znak3==">="){
   			 znak3 = "<=";
    		}
    	}
    	tab3[1][0]=(-a3/b3)*tab3[0][0]+(c3/b3);
    	tab3[1][1]=(-a3/b3)*tab3[0][1]+(c3/b3);
    	tab3[1][2]=(-a3/b3)*tab3[0][2]+(c3/b3);
    	tab3[1][3]=(-a3/b3)*tab3[0][3]+(c3/b3);
    	tab3[1][4]=(-a3/b3)*tab3[0][4]+(c3/b3);
    	tab3[1][5]=(-a3/b3)*tab3[0][5]+(c3/b3);
    
    	/**
    	 * RYSOWANIE WYKRESU
    	 */
    	XYSeries series = new XYSeries("funkcja 1");
		series.add(tab1[0][0], tab1[1][0]);
		series.add(tab1[0][1], tab1[1][1]);
		series.add(tab1[0][2], tab1[1][2]);
		series.add(tab1[0][3], tab1[1][3]);
		series.add(tab1[0][4], tab1[1][4]);
		series.add(tab1[0][5], tab1[1][5]);
		
		XYSeries series2 = new XYSeries("funkcja 2");
		series2.add(tab2[0][0], tab2[1][0]);
		series2.add(tab2[0][1], tab2[1][1]);
		series2.add(tab2[0][2], tab2[1][2]);
		series2.add(tab2[0][3], tab2[1][3]);
		series2.add(tab2[0][4], tab2[1][4]);
		series2.add(tab2[0][5], tab2[1][5]);
		
		XYSeries series3 = new XYSeries("funkcja 3");
		series3.add(tab3[0][0], tab3[1][0]);
		series3.add(tab3[0][1], tab3[1][1]);
		series3.add(tab3[0][2], tab3[1][2]);
		series3.add(tab3[0][3], tab3[1][3]);
		series3.add(tab3[0][4], tab3[1][4]);
		series3.add(tab3[0][5], tab3[1][5]);
		
		XYSeries seriesCEL = new XYSeries("funkcja celu");
		seriesCEL.add(tabcelu[0][0], tabcelu[1][0]);
		seriesCEL.add(tabcelu[0][1], tabcelu[1][1]);
		seriesCEL.add(tabcelu[0][2], tabcelu[1][2]);
		seriesCEL.add(tabcelu[0][3], tabcelu[1][3]);
		seriesCEL.add(tabcelu[0][4], tabcelu[1][4]);
		seriesCEL.add(tabcelu[0][5], tabcelu[1][5]);
		
		XYSeriesCollection dataset = new XYSeriesCollection();
		dataset.addSeries(series);
		dataset.addSeries(series2);
		dataset.addSeries(series3);
		dataset.addSeries(seriesCEL);
		
		double tablicaPrzeciecProstych [][]= new double[3][2];
		//przeciecie 1 z 2
		if(a1!=a2){
		tablicaPrzeciecProstych[0][0]=((b2*c1)-(b1*c2))/(a1*b2-a2*b1); //x
		tablicaPrzeciecProstych[0][1]=(-a1*tablicaPrzeciecProstych[0][0]+c1)/b1; //y
		}
		else { f1=false;}
		//przeciecie 1 z 3
		if(a1!=a3){
		tablicaPrzeciecProstych[1][0]=((b3*c1)-(b1*c3))/(a1*b3-a3*b1);//x
		tablicaPrzeciecProstych[1][1]=(-a1*tablicaPrzeciecProstych[1][0]+c1)/b1;//y
		}
		else { f2=false;}
		//przeciecie 2 z 3
		if(a2!=a3){
		tablicaPrzeciecProstych[2][0]=((b2*c3)-(b3*c2))/(a3*b2-a2*b3); //x
		tablicaPrzeciecProstych[2][1]=(-a2*tablicaPrzeciecProstych[2][0]+c2)/b2; //y
		}
		else { f3=false;}
		
		double tablicaPrzeciecOsiOXOY [][]= new double[6][2];
		//przeciecie 1 z OX i OY
		tablicaPrzeciecOsiOXOY[0][0]=0;//x
		tablicaPrzeciecOsiOXOY[0][1]=c1/b1;//y
		tablicaPrzeciecOsiOXOY[1][0]=c1/a1;//x
		tablicaPrzeciecOsiOXOY[1][1]=0;//y
		//przeciecie 2 z OX i OY
		tablicaPrzeciecOsiOXOY[2][0]=0;//x
		tablicaPrzeciecOsiOXOY[2][1]=c2/b2;//y
		tablicaPrzeciecOsiOXOY[3][0]=c2/a2;//x
		tablicaPrzeciecOsiOXOY[3][1]=0;//y
		//przeciecie 3 z OX i OY
		tablicaPrzeciecOsiOXOY[4][0]=0;//x
		tablicaPrzeciecOsiOXOY[4][1]=c3/b3;//y
		tablicaPrzeciecOsiOXOY[5][0]=c3/a3;//x
		tablicaPrzeciecOsiOXOY[5][1]=0;//y
		
		
		//-------------------------------------ROZWIAZANIE----------------------------------//
		int i=0;//wskazniki
		double tablicaRozwiazan [][]= new double [9][3];
		
		if(tablicaPrzeciecProstych[0][0]>0 && tablicaPrzeciecProstych[0][1]>0){
			tablicaRozwiazan[i][0]=tablicaPrzeciecProstych[0][0]*bc+tablicaPrzeciecProstych[0][1]*ac;
			tablicaRozwiazan[i][1]=tablicaPrzeciecProstych[0][0];
			tablicaRozwiazan[i][2]=tablicaPrzeciecProstych[0][1];
			i+=1;
		}
		if(tablicaPrzeciecProstych[1][0]>0 && tablicaPrzeciecProstych[1][1]>0){
			tablicaRozwiazan[i][0]=tablicaPrzeciecProstych[1][0]*bc+tablicaPrzeciecProstych[1][1]*ac;  // ?????? nie powinno byæ  tablicaPrzeciecProstych[1][1]*ac    ??????? by³o [2][1]
			tablicaRozwiazan[i][1]=tablicaPrzeciecProstych[1][0];
			tablicaRozwiazan[i][2]=tablicaPrzeciecProstych[1][1];
			i+=1;
		}
		if(tablicaPrzeciecProstych[2][0]>0 && tablicaPrzeciecProstych[2][1]>0){
			tablicaRozwiazan[i][0]=tablicaPrzeciecProstych[2][0]*bc+tablicaPrzeciecProstych[2][1]*ac;
			tablicaRozwiazan[i][1]=tablicaPrzeciecProstych[2][0];
			tablicaRozwiazan[i][2]=tablicaPrzeciecProstych[2][1];
			i+=1;
		}
		if(tablicaPrzeciecOsiOXOY[0][1]>0){
			tablicaRozwiazan[i][0]=tablicaPrzeciecOsiOXOY[0][1]*ac; // jesli x1=0 to wzór tu nie powinien byc : bc * x2???
			tablicaRozwiazan[i][1]=0;    //x
			tablicaRozwiazan[i][2]=tablicaPrzeciecOsiOXOY[0][1]; //y  czyli x2
			i+=1;
		}
		if(tablicaPrzeciecOsiOXOY[1][0]>0){
			tablicaRozwiazan[i][0]=tablicaPrzeciecOsiOXOY[1][0]*bc;  // tu zak³adamy ze y czyli x2=0 wiec wzór to chyba ac *x1?? i w linijkacj nizej tez??
			tablicaRozwiazan[i][1]=tablicaPrzeciecOsiOXOY[1][0];
			tablicaRozwiazan[i][2]=0;
			i+=1;
		}if(tablicaPrzeciecOsiOXOY[2][1]>0){
			tablicaRozwiazan[i][0]=tablicaPrzeciecOsiOXOY[2][1]*ac;
			tablicaRozwiazan[i][1]=0;
			tablicaRozwiazan[i][2]=tablicaPrzeciecOsiOXOY[2][1];
			i+=1;
		}if(tablicaPrzeciecOsiOXOY[3][0]>0){
			tablicaRozwiazan[i][0]=tablicaPrzeciecOsiOXOY[3][0]*bc;
			tablicaRozwiazan[i][1]=tablicaPrzeciecOsiOXOY[3][0];
			tablicaRozwiazan[i][2]=0;
			i+=1;
		}if(tablicaPrzeciecOsiOXOY[4][1]>0){
			tablicaRozwiazan[i][0]=tablicaPrzeciecOsiOXOY[4][1]*ac;
			tablicaRozwiazan[i][1]=0;
			tablicaRozwiazan[i][2]=tablicaPrzeciecOsiOXOY[4][1];
			i+=1;
		}if(tablicaPrzeciecOsiOXOY[5][0]>0){
			tablicaRozwiazan[i][0]=tablicaPrzeciecOsiOXOY[5][0]*bc;
			tablicaRozwiazan[i][1]=tablicaPrzeciecOsiOXOY[5][0];
			tablicaRozwiazan[i][2]=0;
			i+=1;
		}
		
		double temp=tablicaRozwiazan[0][0];
		double rozwiazania [] = new double [2] ;
		if(max==true){
		for (int j=0;j<i;j++){
			if (temp < tablicaRozwiazan[j][0]){
				temp = tablicaRozwiazan[j][0];
			rozwiazania[0]=tablicaRozwiazan[j][1];//wspolrzedne x
			rozwiazania[1]=tablicaRozwiazan[j][2];//wspolrzedne y
		}}}
		else
		{
			for (int j=0;j<i;j++){
				if (temp > tablicaRozwiazan[j][0]){
					temp = tablicaRozwiazan[j][0];
				rozwiazania[0]=tablicaRozwiazan[j][1];//wspolrzedne x
				rozwiazania[1]=tablicaRozwiazan[j][2];//wspolrzedne y
			}}
		}
		System.out.println(temp);
		System.out.println(rozwiazania[0]);
		System.out.println(rozwiazania[1]);
		
		//-----------------------OGRANICZENIA--------------------------------------//
		String komunikat = new String("");
		if(znak1!=znak2){
			if(f1==false){
				if((c1>c2 && znak1==">=") || (c1<c2 && znak1=="<=")){
					
				}
			}
			komunikat="ROZWI¥ZANIE JEST!";
		}
		else if(znak3=="<="){
			if((c3<0 && b3>0) || (c3>0 && b3<0)){
				if((a3>0 && b3>0) || (a3<0 && b3<0)){
					komunikat="Brak rozwiazañ dla podanych ograniczeñ, poniewa¿, ¿adna waroœæ funkcji 1 nie zawiera siê w 1. æwiartce";
					//jTextArea1.setText("Brak rozwiazañ dla podanych ograniczeñ, poniewa¿, ¿adna waroœæ funkcji 1 nie zawiera siê w 1. æwiartce");
					//System.out.println("nima");
					}
					else if(znak2=="<=" && c2<0 && a2>0){
						komunikat="Brak rozwiazañ dla podanych ograniczeñ, poniewa¿, ¿adna waroœæ funkcji 2 nie zawiera siê w 1. æwiartce";
						//jTextArea1.setText("Brak rozwiazañ dla podanych ograniczeñ, poniewa¿, ¿adna waroœæ funkcji 2 nie zawiera siê w 1. æwiartce");
					}
					else if(znak3=="<=" && c3<0 && a3>0){
						komunikat="Brak rozwiazañ dla podanych ograniczeñ, poniewa¿, ¿adna waroœæ funkcji 3 nie zawiera siê w 1. æwiartce";
						//jTextArea1.setText("Brak rozwiazañ dla podanych ograniczeñ, poniewa¿, ¿adna waroœæ funkcji 3 nie zawiera siê w 1. æwiartce");
					}
				}
			}
		 
		
		//Tworzymy wykres XY
		JFreeChart chart = ChartFactory.createXYLineChart(
			"Metoda graficzna zadanie 1",//Tytu³
			"OŒ x1", // x-axis Opis
			"OŒ x2", // y-axis Opis
			dataset, // Dane
			PlotOrientation.VERTICAL, // Orjentacja wykresu /HORIZONTAL
			true, // pozka¿ legende
			true, // podpowiedzi tooltips
			false
		);
 
		//Dodanie wykresu do okna
		ChartFrame frame1=new ChartFrame("METODA GRAFICZNA",chart);
		frame1.setVisible(true);
		frame1.setSize(700,700);
    	
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JComboBox jComboBox14;
    private javax.swing.JComboBox jComboBox15;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
